### ISSUE TITLE
Migrar pacote pra null safe

### ISSUE THREAD

**Issue by rodrigobastosv** [rodrigobastosv/search_cep#10]
Migrar pacote pra null safe

**Comment by isorensen** [comment]
+1 para mim. Alguma expectativa de quando estará pronto, @rodrigobastosv ? Está impactando a migração do meu projeto. :-) abs
```
Because search_cep >=2.0.1+1 depends on http ^0.12.1 and project depends on http ^0.13.0, search_cep >=2.0.1+1 is forbidden.

So, because project depends on search_cep ^3.0.0+2, version solving failed.
pub get failed (1; So, because project depends on search_cep ^3.0.0+2, version solving failed.)
exit code 1
```

**Comment by rodrigobastosv** [comment]
@isorensen quando tentei uns dias atrás alguns pacotes que utilizo ainda não tinham sido migrados.

Também to querendo muito migrar logo, mas dependo dos outros pacotes.

Vou analisar hoje se eles migraram.

**Comment by rodrigobastosv** [comment]
@isorensen migrei com sucesso pra null safety :)

Já está disponível na versão 4.0.0-nullsafety.0 no pub.dev.

Tive que subir como pré-release pois estou dependendo de pacotes que ainda estão em pré release
