### ISSUE TITLE
feature: way to cancel the currently running cep validation

### ISSUE THREAD

**Issue by deepak786** [rodrigobastosv/search_cep#12]

**Comment by rodrigovasconceloszup** [comment]
Hi @deepak786 , thanks for using this package.

I don't quite understand what you are trying to do.

Could you please elaborate better? Maybe show you what your use case is.

**Comment by deepak786** [comment]
Hi @rodrigovasconceloszup, 

The use case is below:
1. You entered the CEP (01001-000)
2. It has a valid format.
3. You started doing the validation with API
4. But now you deleted the CEP (either partial or full) (01001-00)
5. CEP validation API is already running
6. You entered the new digit (01001-002)
7. At this time new API will run to validate the CEP and the previous one is also running.
8. There must be a way to cancel the previous call.

**Comment by rodrigovasconceloszup** [comment]
Got it.

I guess this is specific usecase, i don't think i can do that behavior. Maybe makes more sense to do this logic inside your app.

But i'll take some time to see if i figure it out a good solution.

Thanks @deepak786

**Comment by deepak786** [comment]
Yes, the logic will be inside my app. But there must be a way that from your package I can cancel the currently running API validation task.

**Comment by rodrigovasconceloszup** [comment]
It's pretty dificult, because i consume third parties API's. They are not over my control
