### ISSUE TITLE
problema com dart

### ISSUE THREAD

**Issue by paulobreim** [rodrigobastosv/search_cep#13]
A API não funciona mais em Dart, apenas em Dart.
Da a seguinte mensagem:

Because every version of search_cep depends on flutter from sdk which is forbidden, search_cep is forbidden.

**Comment by rodrigobastosv** [comment]
Opa @paulobreim 

Funciona em Dart ou em Flutter?

Vou atualizar as dependencias e deve voltar a funcionar

**Comment by paulobreim** [comment]
Em Dart é que está dando mensagem que não pode usar.
Dart no servidor, portanto sem flutter.

**Comment by rodrigobastosv** [comment]
Qual versão do dart você está usando?

Criei um projeto aqui e rodou de boa com a versão abaixo:

```dart
environment:
  sdk: '>=2.16.1 <3.0.0'
```

**Comment by paulobreim** [comment]
Exatamente a mesma.
Quando colocava pra rodar da o erro:
Because every version of search_cep depends on flutter from sdk which is forbidden, search_cep is forbidden.

Parece ser uma coisa simples de resolver, pelo que vi na internet. Vou ver se faço mais teste. O que posso fazer e um dart create e ai pegar os .dart da versão anterior.

**Comment by rodrigobastosv** [comment]
Blz. Me avisa qualquer coisa!

**Comment by paulobreim** [comment]
problema intermitente. voltou a funcionar.
