### ISSUE TITLE
CEP invalido não dispara erro

### ISSUE THREAD

**Issue by camposmichel** [rodrigobastosv/search_cep#14]
Ao digitar um cep invalido, como `00000000` o erro InvalidCepError não é retornado.

Notei que na api o retorno é da seguinte forma:
https://viacep.com.br/ws/00000000/json

```
{
  "erro": "true"
}
```

Provavelmente a comparação `decodedResponse['erro'] == true` não está dando positivo, pois o true da api é uma string 😵‍💫

Trecho do codigo que necessita desse ajuste:
```
if (response.statusCode == ok) {
        switch (returnType) {
          case SearchInfoType.json:
            final decodedResponse =
                jsonDecode(response.body) as Map<String, dynamic>;

            // TODO: Ajustar esse if
            if (decodedResponse['erro'] == true) {
              return left(const InvalidCepError());
            }

            return right(ViaCepInfo.fromJson(decodedResponse));
```

**Comment by rodrigobastosv** [comment]
Wow @camposmichel , ótimo achado!

Já corrigi e já publiquei a versão 4.0.1 do package. Pode conferir :)

Muito obrigado!
