### ISSUE TITLE
Retornar tipo do erro (enum)

### ISSUE THREAD

**Issue by luizjacomn** [rodrigobastosv/search_cep#2]
Como sugestão, poderia também retornar o tipo do erro (enum `ErrorType`) para facilitar o tratamento no app. No meu caso, informei um cep com formato válido, mas que não existe. Como a mensagem é muito longa, não dá para exibir uma mensagem de erro simples (como pode ver na imagem abaixo). A não ser que compare as Strings, o que não seria uma boa prática.

Ao invés de:
`CEP com formato válido, porém inexistente na base de dados`

Poderia ser apenas:
`CEP inexistente` ou `CEP não existe`

![erro-cep](https://user-images.githubusercontent.com/11355741/72683072-ee033a00-3ab2-11ea-80b5-9386ed6d59eb.png)

**Comment by rodrigobastosv** [comment]
Oi @luizjacomn isso é algo que eu queria ter feito antes mas não tive tempo. Penso em retornar um objeto com um enum de status e a mensagem de erro, desta maneira o usuário poderia optar por mostrar a mensagem de erro ou tratar o status do enum (pra mostrar uma mensagem de erro própria). Acha que fica legal assim?

**Comment by luizjacomn** [comment]
Bom dia @rodrigobastosv. Isso mesmo. Ao meu ver é a melhor opção, pois oferece uma maneira pronta e a opção de personalizar. Agora estou trabalhando em um projeto e estou com o prazo apertado, mas caso você não tenha tempo para implementar até eu terminar, eu posso fazer um pull request. Abraço.

**Comment by rodrigobastosv** [comment]
@luizjacomn devo implementar já hoje isso! Mas obrigado pela ajuda.

**Comment by luizjacomn** [comment]
Show! No aguardo @rodrigobastosv.

**Comment by rodrigobastosv** [comment]
@luizjacomn o ajuste solicitado está na versão 1.0.3, por favor atualizar sua versão.

Basicamente o que fiz foi criar um objeto de erro que vai ser populado com a mensagem e o enum do tipo de erro.

Vou fechar essa issue, mas se ainda faltar alguma coisa pode reabrir a vontade

**Comment by luizjacomn** [comment]
Opa. Obrigado pela atenção. tmj @rodrigobastosv 👊

**Comment by luizjacomn** [comment]
Bom dia @rodrigobastosv. Apenas hoje consegui tempo para testar as alterações que vc fez. Acabei encontrando um probleminha 😅. Como vc pode ver na imagem, estou informando um cep com o formato correto, porém não existe. Ele deveria receber o tipo `ErrorType.nonExistentCep` **(o atributo `errorMessage` está correto)**.
Pelo que eu testei aqui, para os 2 casos está sendo enviado o mesmo tipo **(`ErrorType.invalidCepFormat`)**.
![erro-cep](https://user-images.githubusercontent.com/11355741/73120899-80438c00-3f52-11ea-9673-105b6a87bd3f.png)

**Comment by rodrigobastosv** [comment]
Bom dia @luizjacomn! Obrigado por ter encontrado esse erro. Olharei mais tarde e atualizarei a versão com a correção. Aviso por aqui quando consertar

**Comment by rodrigobastosv** [comment]
Corrigido! Favor atualizar pra versão 1.0.4

**Comment by luizjacomn** [comment]
Vlw @rodrigobastosv. Assim que tiver um tempinho irei atualizar. Mais uma vez obrigado pela atenção! Tmj 👊
