### ISSUE TITLE
Base de CEP desatualizada

### ISSUE THREAD

**Issue by paulobreim** [rodrigobastosv/search_cep#4]
Essa lib usa o viacep.com.br, certo?

Essa base não é uma base atualizada de acordo com a base dos correios.
Em algum momento foi efetuada uma cópia da base mas a base oficial sempre tem atualização.

A lib atende bem a maior parte dos casos, mas a situações que o cep tras nome de Rua errado.

Seria interessante colocar essa informação nas instruções ou usar a própria base dos correios.

**Comment by rodrigobastosv** [comment]
Sim @paulobreim essa lib usa o viacep.

Saberia me dizer se os correios oferecem uma API pública? Acredito que o ajuste não seria muito grande

**Comment by rodrigobastosv** [comment]
Em uma pesquisa rápida não encontrei API pública disponivel deles. Vou procurar com mais cautela depois.

Obrigado por abrir esta issue e me alertar sobre essas inconsistencias. Vou adicionar no README do projeto

**Comment by rodrigobastosv** [comment]
@paulobreim lançei a  versão 2.0.0 do package onde adicionei a possibilidade de utilizar a API do Postmon. Essa versão 2.0.0 tem breaking changes, então se você tiver utilizando uma versão mais antiga do package irá quebrar. Mas não é nada de outro mundo consertar. Reformulei o README para contemplar as mudanças.

Obrigado pelo feedback e por usar o package. Vou fechar essa issue mas sinta-se livre para abri-la se houver mais algum questionamento.

**Comment by paulobreim** [comment]
Esta funcionando perfeitamente.
Parabéns pela rapidez no aprimoramento da solução.
