### ISSUE TITLE
Retornar latitude e longitude do CEP informado

### ISSUE THREAD

**Issue by d-apps** [rodrigobastosv/search_cep#9]
Seria possível implementar para retornar também a latitude e longitude do cep digitado?

**Comment by paulobreim** [comment]
Possível é, mas é simples de implementar na sua aplicação informando a rua e o número.

**Comment by rodrigobastosv** [comment]
Oi @d-apps !

Nenhuma nas API's que utilizo (ViaCep e Postmon) me retorna lat/lon. Não sei se compensa inchar ainda mais o pacote com essa funcionalidade. Como o @paulobreim falou, isto pode ser feito separadamente.

O que você acha?

Qualquer dúvida estou a disposição.

**Comment by rodrigobastosv** [comment]
Nenhuma das API's que utilizo retorna Lat/Lon.

Não queria inchar o pacote com outra implementação, visto que como o @paulobreim falou isto pode ser adicionado de maneira simples.

O que acha @d-apps ?

Qualquer dúvida estou a disposição

**Comment by d-apps** [comment]
> Oi @d-apps !
> 
> Nenhuma nas API's que utilizo (ViaCep e Postmon) me retorna lat/lon. Não sei se compensa inchar ainda mais o pacote com essa funcionalidade. Como o @paulobreim falou, isto pode ser feito separadamente.
> 
> O que você acha?
> 
> Qualquer dúvida estou a disposição.

Tudo bem então, de qualquer forma obrigado.
